### PR TITLE
upstream

### PR DESCRIPTION
**Pull request by WesleyVanNeck**

### CODE REVIEW

**Comment by Mathias-Boulay** [comment]
Why upstream does have +12k lines ?! 👀 
I don't remember being so late 😭

**Comment by WesleyVanNeck** [comment]
> Why upstream does have +12k lines ?! 👀
> I don't remember being so late 😭

dosnt aks me i think therew ere a lot of comits

**Comment by Mathias-Boulay** [comment]
Fuck this whole upstream is almost 20k worth of stuff

**Comment by Mathias-Boulay** [comment]
Welp, I hope nothing breaks.
Here we go

**Pull request merged**
